{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rtdwh-mgmt.serviceAccountName" . }}
  labels:
    {{- include "rtdwh-mgmt.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
